set(_CATKIN_CURRENT_PACKAGE "bird_detection")
set(bird_detection_VERSION "0.0.0")
set(bird_detection_MAINTAINER "goelshivam12 <goelshivam12@todo.todo>")
set(bird_detection_PACKAGE_FORMAT "1")
set(bird_detection_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bird_detection_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bird_detection_BUILDTOOL_DEPENDS "catkin")
set(bird_detection_BUILDTOOL_EXPORT_DEPENDS )
set(bird_detection_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(bird_detection_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(bird_detection_TEST_DEPENDS )
set(bird_detection_DOC_DEPENDS )
set(bird_detection_DEPRECATED "")